name: Publish
on:
   workflow_call:
      secrets:
         NPM_TOKEN:
            required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
              fetch-depth: 0
              persist-credentials: false 

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm install

      - run: npm run build
               
      - name: Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' 
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
